# Generated by Django 2.2.4 on 2019-08-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0002_auto_20190809_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
