# Generated by Django 2.2.4 on 2019-08-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0003_auto_20190812_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='default_category', max_length=200),
        ),
    ]
