# Generated by Django 2.2.4 on 2019-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0004_auto_20190812_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
