# Generated by Django 2.2.4 on 2019-08-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0005_expense_month_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month_number',
            field=models.IntegerField(db_column='month_number'),
        ),
    ]
