# Generated by Django 2.2.4 on 2019-08-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0006_auto_20190812_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month_number',
            field=models.IntegerField(),
        ),
    ]
