# Generated by Django 2.2.4 on 2019-08-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0008_auto_20190812_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month_number',
        ),
    ]
