# Generated by Django 2.2.4 on 2019-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0009_remove_expense_month_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month_number',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
